version: '3'

services:

  nodejs:
    build:
      context: node
    container_name: nodejs
    networks: 
      - desafio-docker-node

  nginx-node:
    build: 
      context: nginx
    container_name: nginx-node
    networks:
      - desafio-docker-node
    ports:
      - "3000:80"

networks:
  desafio-docker-node:
    driver: bridge