version: '3'

services:

  nodejs:
    build:
      context: node
    container_name: nodejs
    networks: 
      - desafio-docker-node

  mysql-database:
    build:
      context: mysql
    command: --innodb-use-native-aio=0
    container_name: database
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - desafio-docker-node

  nginx-node:
    build: 
      context: nginx
    container_name: nginx-node
    networks:
      - desafio-docker-node
    ports:
      - "3000:80"

networks:
  desafio-docker-node:
    driver: bridge